apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: express-app
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: express-app
  namespaceSelector:
    matchNames:
      - cicd-platform
  endpoints:
    - port: http
      path: /metrics
      interval: 15s