apiVersion: v1
kind: Service
metadata:
  name: express-app
  namespace: cicd-platform
  labels:
    app: express-app
spec:
  selector:
    app: express-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP